OpenSourceCommunityBrasil/REST-DataWare

CORE/Source/Basic/uRESTDWBasicDB.pas
- Melhoria na função ScanParams (novo código)
=> Função ScanParams

CORE/Source/uRESTDWPoolerDB.pas
Melhoria na Funcção ScanParam (novo código)
=> Funcao ScanParams

CORE/Source/Connectors/FireDAC/uRESTDWDriverFD.pas, CORE/Source/libs/uDWConsts.pas, CORE/Source/libs/uDWJSONObject.pas, CORE/Source/libs/uDWMassiveBuffer.pas
- ScanParams : Correção de SQL Injection na unit do componente MassiveBuffer
- Params de Query do tipo strings e vazias era tratadas como nulas pelo servidor, agora string ""="" e null=null
=> Correções Diversas

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Plugins/Memdataset/uRESTDWDataset.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/libs/uRESTDWMassiveBuffer.pas
Correção BasicDB: CopyParams (AccessTag, WelcomeMessage) Correção IdBase: Concatenação de mensagens de erro (apenas quando for diferente).
- Ajuste em data/hora com binary Correção de memleak do massiveobject em Delphi/Lazarus
=> Merged revision(s) 3183-3186 from SourceForge/trunk:

CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Plugins/DMDados/uRESTDWDatamodule.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas
- Parser de URL e Params do ServerMethod com novas implemantocoes
-- Params Query + Params URI, funcionando Juntos 
-- Implementado rota para o DefaultEvent do ServerEvents
-- Resolvido erro: #91
- Variaveis do AccessTag e WelcomeMessage e demais recebidas por POST, com pequenos bugs de entrada
-- Resolvido bug: #94
=> Novas Implementações e Correções

CORE/Source/Basic/uRESTDWDesignReg.pas, CORE/Source/Database_Drivers/uRESTDWAnyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWApolloDBDriver.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWFireDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWLazSQLDriver.pas, CORE/Source/Database_Drivers/uRESTDWMyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWUniDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas
Ajuste na propriedade Connection dos Drivers
=> Ajustes Novos Drivers

CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Troca na descricao das funcoes da Classe TRESTDWDriverBase:
-- RDWDataTypeFieldName, RDWDataTypeParamName, RDWDataTypeField, RDWDataTypeParam para
-- RESTDWDataTypeFieldName, RESTDWDataTypeParamName, RESTDWDataTypeField, RESTDWDataTypeParam
=> Mudanças na descrição das funções

CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWUniDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas
- SaveToStream dos Drivers UNIDAC e ZEOS, agora nativos
- Adicionado SaveToStreamCompatibleMode na classe do DriverBase
- Criado classe para Buscar Parametros de Qualquer SGBD (TRDWDrvParams)
- Criado classe TRDWDrvParam para converter Param de qualquer SGBD
=> Correções e Implementacoes

CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- ParamsList movida para o TRESTDWDrvDataset, problemas com conexoes simultaneas
=> Correcoes do DriverBase - ParamsList

CORE/Source/Database_Drivers/uRESTDWAnyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWApolloDBDriver.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWFireDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWLazSQLDriver.pas, CORE/Source/Database_Drivers/uRESTDWUniDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas
- Drive Base:
-- Criado Funcao LoadFromStreamParam para salvar stream nos params de cada Driver -- Pequenos Bugs corrigidos
-- Add de Variavel detectando o ServerMethod (FServerMethod), para chamada de eventos
- Demais Drivers -- Implementado funcão LoadFromStreamParam
-- Driver Zeos apatado como versoes 7 e 8 
-- Driver UniDAC, adição de Transaction
- Correcoes para funcionalidades com Delphi 7
=> Implemantações, Correçoes e Melhorias

CORE/Source/Database_Drivers/uRESTDWAnyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWApolloDBDriver.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWFireDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWLazSQLDriver.pas, CORE/Source/Database_Drivers/uRESTDWMyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWUniDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas
- Driver AnyDAC corrigido e funcional com Delphi 7
- Driver MyDAC implementado LoadFromStreamParam, e adaptado com Transaction (igual UNIDAC)
- Demais Drivers - Adaptacoes para funcionar com o Delphi 7 (consts)
=> Implementações

CORE/Source/Database_Drivers/uRESTDWApolloDBDriver.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWInterbaseDriver.pas
- Implementado Driver Novo da aba Interbase (IBX)
- Adaptações das funcionalidades para Driver ApolloDB
- Criado propriedade pública para acesso de Propriedades do ServerMethod no driver
=> Implementações e funcionalidades

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWDesignReg.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/Sockets/Indy/uRESTDWIdReg.pas
Remoção do antigo RESTDWPoolerList que estava com AbstractError e criação do RESTDWIdPoolerList
=> Criação do RESTDWIdPoolerList

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDW.pas, CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDWBase.pas, CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDWDef.pas, CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDWMeta.pas
- uRESTDWBasicDB - Correção TRESTDWDatabasebaseBase  SetConnection = False o vAuthOptionParams = nil
- Novas Imprementações para o PhysFireDAC adapatado para Stream e MemDataset Novo
=> - Novas Implementações e correções

CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDWBase.pas, CORE/Source/Database_Drivers/FDPhysic/FireDAC.Phys.RDWMeta.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Pequena modificação no driver base (uRESTDWDriverBase) para receber o SQL do cliente
- PhysicDriverFiredac funcionando com FDQuery e FDTable
=> Novas Implementações

CORE/Source/utils/uRESTDWTools.pas
- funcao DWFieldTypeToFieldType conversão de datatype para Lazarus
=> - adaptações do storage binario para lazarus

CORE/Source/Basic/uRESTDWStorageBinRDW.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/utils/uRESTDWTools.pas
- Adaptações para Fields BCD, FmtBCD, FixedWideChar, WideString, WideMemo
=> - Correção de Datatypes para Lazarus

CORE/Source/utils/uRESTDWTools.pas
- Adaptação de Field TFieldTimeStamp para Lazarus (não implementado pela unit DB)
=> - Correção de FieldType TimeStamp

CORE/Source/Basic/uRESTDWStorageBinRDW.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correções de IFDEFs para Delphi (uRESTDWMemoryDataset)
- Adaptação para Delphi 7 (uRESTDWStorageBinRDW)
=> Adaptações para compatibilidade com Delphi

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Correção para funções de GetTableNames, GetFieldNames, GetProcParams, GetKeyFieldNames (Trim e UnQuoted)
- Adaptação para List TableName para FDTable e FDQuery (PhysFireDAC)
=> - Correções no DriversBase

CORE/Source/Basic/uRESTDWDesignReg.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.dfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.lfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas
- Mudanças para a propriedade UpdateTableName do RESTDWClientSQL, listar as Tabelas do Servidor
- Adicionado Label "Executed Time" no SQLEditor
- Corrigido ação de fechar e projeto ser alterado (poder resalvá-lo)
- Modificado mensagem de "Realmente Desaja Sair?" somente ao Cancelar um SQL que foi modificado
- Funcao GetTableNames devolvendo lista ordenada das tabelas
=> Implementações para ClienteSQL e SQLEditor

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Correção de WideString, DateTime para StorageBin
- Correção de WideMemo para PhysFireDac
- Retirado Prepare do ImportParams (DriverBase), problemas com MSSQL
=> - Correção de WideString, Datetime e ImportParams DriversBase

CORE/Source/utils/uRESTDWOpenSslLib.pas
- Correções em diretiva e funcão UnloadLibrary
=> Adaptações para compilar e Delphi

CORE/Source/Plugins/SelfSigned/uRESTDWSelfSigned.pas, CORE/Source/utils/uRESTDWOpenSslLib.pas
Adaptações para funcionar com Delphi7
=> SelfSigned Delphi7

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/utils/uRESTDWJSONObject.pas, CORE/Source/utils/uRESTDWMassiveBuffer.pas
- Ajustes no tratamento de erros no evento de Exclusão;
- Ajuste no conteúdo de campos Datetime na gravação com e sem ReflectChanges;
- Ajustes na inserção de dados utilizando MassiveCache.
=> Ajustes realizados juntos com o Gilberto.

CORE/Source/utils/uRESTDWJSONObject.pas
=> Correção do último Merge.

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Adaptações no StorageBin para Leitura de Gravacao
- Criado Funcoes de SaveToFile e LoadFromFile no StorageBase
- Adaptações do CalcFieldLen de conforme os campos de StorageBin
=> - Adaptações e Implementações no StorageBin

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção de WideMemo no StorageBin
- Adaptação de TimeStampOffSet para Lazarus e Delphi7
- Correção no CalcFieldLen de Campos Wide
=> - Correções para Campos Wide (StorageBin)

CORE/Source/Basic/uRESTDWStorageBin.pas
- Correção de Bug na Leitura dos Dados
- Correção de Bug de tratamento de Nulos
=> - Correção na Leitura StorageBin

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas
- Implementado Classe de Exception para tratamento de Erros
- Implementado para uso de "Transactions"
- Correção de WideString e FixeWideString
=> Melhorias RESTDWPhysFiredac, Adicionado Transactions

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas
- Correção de WideString na leitura dos campos (PhysFireDAC)
=> PhysFireDAC - Correção WideString

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWMeta.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Conserto de Campos String (UTF8)
- Melhora para leitura de Tabelas (PhysFireDAC)
=> Correções para PhysFireDAC

CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.dfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.lfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas
- Fixed issue #178 
- Fixed issue #179 
- Fixed issue #180
=> Fixes SQLEditor

CORE/Source/Database_Drivers/uRESTDWDriverBase.pas
- Correção no GetTableNames para PostgreSQL
=> - DriversBase erro de GetTableNames PostgreSQL

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWMeta.pas
- Correção para listas de tabelas, listando com aspas
- Início de implementações para melhor adaptação com dos metadados
=> PhysFireDAC - Adaptações no metadados

CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas
- Correção de Erro no processamento do MassiveCache contendo mais de uma operação.
- Correção do controle de Transações no Drive Zeos.
=> Correção de Erro no processamento do MassiveCache

CORE/Source/Database_Drivers/ZeosPhysLink/RESTDWZeosPhysLink.dpk, CORE/Source/Database_Drivers/ZeosPhysLink/RESTDWZeosPhysLink.dproj, CORE/Source/Database_Drivers/ZeosPhysLink/ZDbcRESTDW.pas, CORE/Source/Database_Drivers/ZeosPhysLink/ZDbcRESTDWMetadata.pas, CORE/Source/Database_Drivers/ZeosPhysLink/ZDbcRESTDWStatement.pas, CORE/Source/Database_Drivers/ZeosPhysLink/ZPlainRESTDWDriver.pas, CORE/Source/Database_Drivers/ZeosPhysLink/ZRESTDWAnalyser.pas, CORE/Source/Database_Drivers/ZeosPhysLink/ZRESTDWToken.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZeosPhysLink.pas
- Iniciando implementações para PhysZeosLink
=> ZeosPhysLink

CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZAnalyser.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbc.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcMetadata.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcStatement.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZPlainDriver.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZToken.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZeosPhysLink.pas
- Troca no nome das units do PhysZeos
=> PhyZeos - nome das units

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcStatement.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZeosPhysLink.pas
- PhysZeos
-- 99.9% completo funcionando com Delphi (Testado com Firebird)
- PhysFireDAC
-- Correção de Leitura e tratamento de Blobs
- StorageBin
-- Correção de Leitura de Integer para Datasets (não RESTDWMemDataset)
=> PhysZeos, PhysFireDAC + Correções

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZAnalyser.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbc.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcMetadata.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcStatement.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZPlainDriver.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZToken.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZeosPhysLink.pas
- PhysZeos - Adaptado para Zeos 7 e Zeos 8
- PhysZeos - Pronto Compilando em Lazarus e Delphi
- PhysFireDAC - Correções de Defines
=> PhysZeos funcionando Delphi e Lazarus

CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbc.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcStatement.pas
- Correção para criar o pacote de instalação do componente PhysZeos
=> - PhysZeos

CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZAnalyser.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbc.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcMetadata.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcStatement.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZPlainDriver.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZToken.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZeosPhysLink.pas
- Adicionado cabeçalho do Projeto RestDataware nos arquivos do ZeosPhys
- Correção para Instalar DriverZeos e PhysZeos com Zeos 8
=> ZeosPhys funcionando com Zeos 8

CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.dfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.lfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas
- Correção do SQLEditor não estava gravando a alteração do SQL (Corrigido)
=> SQLEditor não grava o SQL editado

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Corrigido para compilar em Lazarus
=> - RESTDWMemoryDataset

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção função DataEvent - Para Lazarus
=> RESTDWMomeryDataset - correções para instalacao Lazarus

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas
- Melhorias na leitura dos fontes (RESDWStorageBin)
- RESTDWMemoryDataset - correção para leitura e escrita de DateTime, Date, Time
- RESTDWSQLEditor - Correção para Delphi7
=> RESTDWMemoryDataset correcoes de leitura e escrita

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Corrigido bug de conversao de Date, Time e DateTime
=> RESTDWMemoryDataset - correção para Lazarus

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção de RecordCount para Filter
- Correção de StateChange para Filters
=> RESTDWMemoryDataset - 88% Pronto

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Implementação IndexFieldNames -> SortOnFields
=> RESTDWMemoryDataset - Ordenando Registros

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção para calcFields -  não estava lendo
- Correção para Datasets, ja carregadas com fields
- Correção de fields DateTime -> calcFieldSize
=> RESTDWMemoryDataset - correções 

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção LoadFromStream - update Grid
- Correção Leitura de WideString
- Correção de Sort - String e WideString
=> - RESTDWMemoryDataset - correções

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção de variáveis com nome reservados
=> RESTDWMemoryDataset - correções para Lazarus

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Inicio das implementações do Delta (Status do Record)
- Correção SortFields - AV
- Criado funcoes Locate e Lookup
- Adaptações para Lazarus
=> RESTDWMemoryDataset

CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWBasicTypes.pas, CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Includes/uRESTDW.inc, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/utils/JSON/uRESTDWJSON.pas, CORE/Source/utils/uRESTDWJSONObject.pas, CORE/Source/utils/uRESTDWTools.pas, CORE/Source/utils/uRESTDWZlib.pas
Correção novas diretivas para Delphi Linux
=> Correção novas diretivas para Delphi Linux

CORE/Packages/Delphi/RESTDWCore.dproj, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Correção de redundância de include em .dproj.
=>  - Correção de typo em diretiva da MemoryDataSet.

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas, CORE/Source/Database_Drivers/ZeosPhysLink/uRESTDWZDbcResultSet.pas
- Adaptações de Save e Load para StorageBin
- Adaptações de Load no PhysFireDAC
- Adaptações de Load no PhysZeos
=> - Correções de StorageBin e PhysDrivers

CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Database_Drivers/uRESTDWFireDACDriver.pas
com Server Linux ou Windows e/ou Cliente Linux ou windows
=> Correção de charset para o Physycs driver firedac 

CORE/Source/Basic/uRESTDWBasic.pas
=> Correção para eventos na transferencia de arquivos em ovblob

CORE/Source/Sockets/Indy/uRESTDWIdBase.pas
=> Correção de erro parametro ovblob e possivelmente outros do lado do cliente

CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
Se Deus quiser vai estabilizar...
=> Corrige erro em campo tipo BCD,FMTBCD para TRESTDWClientSQL

CORE/Source/Basic/Mechanics/uRESTDWAuthenticators.pas, CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Sockets/Ics/uRESTDWIcsBase.pas
Mudanças no ICS: 
- Ajuste no Envio dos Headers para o CORS funcionar
- Permissão para receber requisições OPTIONS, DELETE e PUT
- Correção de AV nas Requisições OPTIONS, DELETE e PUT
Mudanças nos Authenticators:
- Remoção da AuthMessages
- Ajuste na Indentação
=> Ajustes no ICS e nos Authenticators

CORE/Source/Sockets/Fphttp/uRESTDWFphttpBase.pas
Ajustes internos.
Com a ajuda do Ari, Fernando e Fábio, o componente já pode ser instalado e usado o service pooler, ainda com ausência de algumas funcionalidades, mas já responde.
=> Ajustes no componente uRESTDWFphttpBase

CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWServerContext.pas, CORE/Source/Basic/uRESTDWServerEvents.pas, CORE/Source/Basic/uRESTDWServerMethodClass.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/ShellTools/uRESTDWShellServicesDelphi.pas, CORE/Source/ShellTools/uRESTDWShellServicesLazarus.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/utils/uRESTDWJSONObject.pas, CORE/Source/utils/uRESTDWMassiveBuffer.pas, CORE/Source/utils/uRESTDWTools.pas
- Correção de serialização de PATCH parâmetro
- Correção do Eventname e do ContextName em LAzarus.
- Correção para uso de ISAPI/CGI no IIS
- Correção Binario physics driver
- Ajuste feito no DM de RESTDW pelo Brito reproduzido na ServerMethodClass.
- Correção de bookmark do novo dwmemtable para lazarus.
- Correção Binario Clientsql
- Correções no RESTDWmemtable para uso no Lazarus.
- Massive Edit, Delete e Insert Fix.
- Reopen data Fix.
- CloseData fix.
- Correções de memleak no Lazarus no dwmem
=> Atualização

CORE/Packages/Lazarus/RESTDataWareComponents.lpk, CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/utils/JSON/uRESTDWDataJSON.pas, CORE/Source/utils/JSON/uRESTDWJSON.pas, CORE/Source/utils/uRESTDWMassiveBuffer.pas
feat: adicionar TExtendedField registrado no IDE (Lazarus/Delphi)
fix(json): corrigir serialização e destruição de arrays no serializador
fix(restdwmemtable): corrigir TExtendedValue no SetBuffer (Lazarus)
fix(buffer): ajuste no Buffer para Delphi
fix(massive): corrigir comportamento de Massive em Delphi/Lazarus
chore(cgi): atualizar módulo CGI no Lazarus
chore(ui): modificar formulário
=> Adição de TExtendedField e correções em JSON, Buffer e Massive
