OpenSourceCommunityBrasil/REST-DataWare

CORE/Source/uRESTDWBase.pas
1 - correção para o issue 'Server Events com context no Lazarus Windows não funciona'
2 - correção para 'Server Contexts no Delphi Windows que não encontra nenhum Context'
(questões parecidas, mas diferentes)
=> Correção para Server Event not found; correção para Server Context not found

CORE/Source/Basic/uRESTDWBasicDB.pas
São 3 alterações:   
- o Access Violation,  
- Ajuste para permitir inherited
- Correção para permitir gravação quando houver Trigger na tabela no SQL-Server
Corrigindo erro de Access Violation ao indicar um parâmetro que não existe, na propriedade ParamByName do TRESTDWClientSQL.
Correção seguindo a mesma lógica do Standard do FireDac:
function TFDDataSet.ParamByName(const AValue: string): TFDParam;
begin
Result := Params.ParamByName(AValue);
end;
function TFDParams.ParamByName(const AValue: String): TFDParam;
begin
Result := FindParam(AValue);
if Result = nil then
DatabaseErrorFmt(SParameterNotFound, [AValue], GetDataSet);
end;
=> Corrigindo erro Access Violation ao indicar ParamByName

CORE/Source/Consts/uRESTDWConsts.pas, CORE/Source/utils/uRESTDWJSONObject.pas
Permitir escolher entre UPPERCASE, lowercase e CamelCase no Retorno do JSONValue quando é usado o .LoadFromDataSet
=> Permitir cases diferentes do JSON de retorno do JSONValue 

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas
- Correção da Exceção do ExecuteCommand para receber no ApplyUpdates do FDTable (Ao se conectar usando Autenticação (Bearer ou Token), sem RenewToken, com LifeCycle=10), forçando o Servidor a dar erro 401 - Unauthorized e não gravar o registro no banco e sim dar a mensagem de exceção) ->> by Eloy (rsrsrsrsrs)
=> - Correção do PhysFireDAC - Tratamento de Exceções

CORE/Source/Basic/uRESTDWBasicDB.pas
- Removido variável vParamCount do RESTDWClientSQL e RESTDWTable
- Resolvido problema de entrada de parâmetros Inválidos
=> - Erro de Param inválido TRESTDWClienteSQL

CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.dfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.lfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas
- Alteração na escrita da propriedade SQL do RESTDWClientSQL, permitindo escrever sem user SQLEditor
- SQLEditor abrindo sem travar, por falhas de não estar conectado
- Adaptado thread para buscar Tables e Fields no SQLEditor
=> - SQLEditor abrindo sem travar

CORE/Source/Database_Drivers/FireDACPhysLink/FireDAC.Phys.RESTDWBase.pas
- Correção de campo InternalCalc no PhysFireDAC
=> PhysFireDAC - Erro campo InternalCalc

CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/uRESTDWAnyDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Database_Drivers/uRESTDWFireDACDriver.pas, CORE/Source/Database_Drivers/uRESTDWZeosDriver.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
- Implementado getQuery Unidirecional -> para export datasets
- RESTDWMemoryDataset - Retirado AV do Lazarus
- Funções de exportação de dados - readaptadas para funcionar com queries Unidirecional
=> Server Drivers com query Unidirecional + RESTDWMemoryDataset 95% Pronto

CORE/Source/Basic/uRESTDWBasicDB.pas
Correção MasterDetail com parâmetros extras.
Quanto um TRDWClientSQL está associado a outro com MasterDetail eles se ligam através dos paramentes, porém estava limpando parâmetros extras que não são campos na query principal.
=> Correção MasterDetail com parâmetros extras

CORE/Source/Basic/Mechanics/uRESTDWMessageCoderMIME.pas
Incluído "Destructor Destroy" na Classe TRESTDWMessageDecoderMIME.
=> Correção de memory Leak unit uRESTDWMessageCoderMIME.pas

CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
Ao fechar a aplicação cliente, sem dar o Close na Tabela (ClientSQL), estava gerando memory leak.
=> Remoção Memory Leak do TRESTDWMemTable.

CORE/Source/Sockets/Indy/uRESTDWIdBase.pas
No Datamodule do RDW, no evento OnGetToken, a variável TokenID, estava vindo vazia.
=> Resolve problemas da autenticação Token. by Guilherme Discher

CORE/Source/Basic/uRESTDWBasic.pas
A propriedade NeedAuthorization 
estava a ativar o evento AuthRequest quando estava desativado
=> corrigido Parametro NeedAuthorization dos eventos

CORE/Source/Basic/uRESTDWStorageBin.pas
Esse problema estava afetando a compilação em x64.
=> Correção a alteração do Anderson: inicialização do var "r" (int64) não estava a ser inicializado com 0

CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Sockets/Fphttp/uRESTDWFphttpBase.pas
Correção no tratamento do vErrorMessage no onWelcomeMessage da uRESTDWBasic. Ajustes internos na uRESTDWFphttpBase
=> Ajuste na uRESTDWBasic e uRESTDWFphttpBase

CORE/Source/Sockets/Fphttp/uRESTDWFphttpBase.pas
Ajustado para pedir login e senha quando usar autenticação básica via browser.
=> Ajustes uRESTDWFphttpBase

CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Sockets/Fphttp/uRESTDWFphttpBase.pas
Ajuste para tratamento do Accept e ErrorMessage do WelcomeMessage Ajustes nos parâmetros do commandexec.
=> Ajustes uRESTDWBasic e uRESTDWFphttpBase

CORE/Source/Basic/Mechanics/uRESTDWAuthenticators.pas, CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Plugins/DMDados/uRESTDWDatamodule.pas
Remoção da lógica de autenticação do CommandExec e volta dos Eventos no DataModule
=> Remoção da Autenticação do CommandExec

CORE/Packages/Delphi/Connectors/Indy/RESTDWSocketIndy.dof, CORE/Packages/Delphi/Connectors/Indy/RESTDWSocketIndy.dproj, CORE/Packages/Delphi/RESTDWCore.dproj, CORE/Packages/Delphi/ShellTools/RESTDWShellServicesDesign.dof, CORE/Source/Basic/Mechanics/uRESTDWBuffer.pas, CORE/Source/Basic/Mechanics/uRESTDWCoder.pas, CORE/Source/Basic/Mechanics/uRESTDWDataUtils.pas, CORE/Source/Basic/Mechanics/uRESTDWMessageCoder.pas, CORE/Source/Basic/Mechanics/uRESTDWMessageCoderMIME.pas, CORE/Source/Basic/uRESTDWBasic.pas, CORE/Source/Basic/uRESTDWBasicClass.pas, CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWBasicTypes.pas, CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Basic/uRESTDWResponseTranslator.pas, CORE/Source/Basic/uRESTDWServerContext.pas, CORE/Source/Basic/uRESTDWServerEvents.pas, CORE/Source/Basic/uRESTDWServerMethodClass.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Basic/uRESTDWStorageJSON.pas, CORE/Source/Plugins/DMDados/uRESTDWDatamodule.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemVCLUtils.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/utils/JSON/uRESTDWDataJSON.pas, CORE/Source/utils/JSON/uRESTDWJSON.pas, CORE/Source/utils/JSON/uRESTDWJSONInterface.pas, CORE/Source/utils/uRESTDWJSONObject.pas, CORE/Source/utils/uRESTDWTools.pas
- Correção para uso de Rotas com e sem autorização.
- Correção da WriteToDataset para FireDAC e outros.
- Correção na JSON Interface para accessviolation parar em arrays e outros valores null.
- Correção de MemoryLeak (TRESTDWMessageDecoderMIME)
- Correção de MemoryLeak quando autenticação Bearer/Token (TRESTDWJSONInterfaceObject)
- Remoção de memleaks nas classes JSON internas do RESTDataware.
- Remoção de memleaks no WriteToDataset.
- Ajuste de Compilação Lazarus e Delphi's antigos dos novos fixes.
- Correção Memory Leaks uRESTDWJSONInterface (TJSONArray)
- Fix do Indice de Strings para FMX Linux/Android.
- Correções do Método Put para novas integrações.
- Correções para campos ORABlob no ClientSQL e dwMemtable.
- Correção para compilação delphi Linux,
- correção para deamons …
=> Atualização

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWParams.pas, CORE/Source/Basic/uRESTDWServerContext.pas, CORE/Source/Basic/uRESTDWServerEvents.pas, CORE/Source/Consts/uRESTDWConsts.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.dfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.lfm, CORE/Source/Plugins/SQLEditor/uRESTDWSqlEditor.pas, CORE/Source/utils/uRESTDWMassiveBuffer.pas
---
- Correções de compilação para **Lazarus e FPC**.
- Correção de `FreeMem` para Lazarus/Delphi antigos no binário.
- Correção para **set de dados Timestamp** em Lazarus/FPC.
- Correção no `ServerContext` em **modo visual** para Lazarus/Delphi.
- Correção de `IndexDefs`.
- Ajustes na **IDE**, nome de eventos e parâmetros dos eventos no Lazarus.
- Correção do exemplo **FileTransfer** para Lazarus no Windows.
- Correção do exemplo **Client do FileTransfer**.
- Correção do exemplo **FullClient**, permitindo que, ao clicar no título, um índice seja selecionado no campo correspondente via `IndexDefs`.
- Melhoria no exemplo **ClientSQL**.
- Ajustes gerais nos **demos** para Lazarus e Delphi.
- Correção no `Get Server Events`.
- Correção de `DriverBase` para gravação de **dados nulos** em …
=> Novas Atualizações

CORE/Packages/Delphi/RESTDWCore.dpk, CORE/Source/Basic/uRESTDWProtoTypes.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Database_Drivers/uRESTDWDriverBase.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/utils/uRESTDWTools.pas
- Ajuste de campos Single para Float.
- Substituição de FmtBCD/BCD por Extended personalizados.
- Suporte a Extended em Delphi antigos, Lazarus e FPC puro.
- Compatibilização de clientes SQL com o servidor Delphi.
=> Correções de tipagens e compatibilidade Delphi/Lazarus

CORE/Source/Basic/uRESTDWBasicDB.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Consts/uRESTDWConsts.pas, CORE/Source/Sockets/Indy/uRESTDWIdBase.pas, CORE/Source/utils/JSON/uRESTDWJSON.pas, CORE/Source/utils/JSON/uRESTDWJSONInterface.pas, CORE/Source/utils/uRESTDWTools.pas
- Suporte a campos ftArray como String (limite inicial 255).
- Correções de Null/NullClass na JsonInterface (inclui Lazarus).
- Remoção de memory leaks em Lazarus/FPC.
- Propriedade BinaryRequest removida do ClientSQL (padrão binário será no ClientPooler).
- Ajuste da numeração de versão.
=> Ajustes em ftArray, JsonInterface e ClientSQL

CORE/Source/Basic/uRESTDWDesignReg.pas, CORE/Source/Basic/uRESTDWStorageBin.pas, CORE/Source/Plugins/Memdataset/uRESTDWMemoryDataset.pas
Adicionada a Classe TExtendedField em Campos Registrados no IDE em Lazarus e Delphi
=> Versão Release 2.1.0
